# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Use rubocop in conjunction with ruby-lsp (faster formatter, no configurable rules)
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideHashLiteralBrackets:
  Enabled: false
